version: '3.8'  # Docker Compose 파일 버전 설정

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=db
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - db
      - mlflow
    volumes:
      - ./static:/code/static
      - ./templates:/code/templates
      - ./mlruns:/mlflow/mlruns  # MLflow 로그 저장 위치 추가

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  mlflow:
    image: mlflow/mlflow:2.2.2  # 최신 MLflow 버전으로 변경
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    ports:
      - "5000:5000"  # MLflow 서버 포트
    volumes:
      - ./mlruns:/mlflow/mlruns  # MLflow 실험 로그를 저장할 디렉토리 마운트

volumes:
  postgres_data:
  mlruns:
