services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./static:/code/static
      - ./templates:/code/templates
      - ./mlruns:/mlflow/mlruns
      - ./sqlite_data:/code/sqlite_data  # SQLite 데이터 저장 위치 추가

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.0.1
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns

volumes:
  sqlite_data:
