stages:
  prepare:
    cmd: python scripts/prepare.py
    deps:
      - data/raw/eeg_raw_data.csv
    outs:
      - data/processed/eeg_train_data.csv
      - data/processed/eeg_test_data.csv

  train:
    cmd: python scripts/train.py
    deps:
      - data/processed/eeg_train_data.csv
      - hyperparameters.yaml
    outs:
      - models/model.pkl

  evaluate:
    cmd: python scripts/evaluate.py
    deps:
      - models/model.pkl
      - data/processed/eeg_test_data.csv
    metrics:
      - metrics/eeg_metrics.json
